# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Container CD

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Generate Style Tag
        run: node twind.processor.js

      - name: Remove Dev HTML
        run: rm src/assets/dev.html

      - name: Minify HTML
        run: npx minify src/assets/index.html > src/assets/.index.html && mv src/assets/.index.html src/assets/index.html

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ryanchristian4427/github-contribution-calendar-api
          tags: latest
